-- Empresa Gestor Pro
--
-- Este arquivo antigo não contém mais o schema permissivo original.
-- Execute o arquivo abaixo no Supabase SQL Editor, primeiro em homologação:
-- supabase/migrations/20260820_secure_gestor_pro.sql
--
-- A migração remove o acesso anônimo, cria RLS por empresa/função,
-- configura o bucket privado e adiciona as transações de venda.

-- O schema legado do ToriMarket foi preservado apenas no histórico/migrations.
-- Não execute policies anon_full_* em novos ambientes.
